#!/usr/bin/env python3
"""Compile AGENTS.md / CLAUDE.md files from modular docs sources."""

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent

REPO_GENERATED_NOTE = (
    "<!-- Generated for repository development workflows. Do not edit directly. -->"
)
LAB_GENERATED_NOTE = "\n".join(
    [
        "> Managed by Prime Lab. Do not edit this file directly.",
        "> `prime lab setup` and `prime lab sync` refresh it. Put project-specific agent guidance in workspace-root `AGENTS.local.md`; agents should read that file after this one if it exists.",
    ]
)


def read_without_title(path: Path) -> str:
    """Read a markdown file, skipping its first title line and leading blank lines."""
    lines = path.read_text().splitlines()
    start = 1
    while start < len(lines) and lines[start].strip() == "":
        start += 1
    return "\n".join(lines[start:]).strip()


def read_markdown(path: Path) -> str:
    """Read markdown and trim outer whitespace."""
    return path.read_text().strip()


def combine_sections(sections: list[str]) -> str:
    """Combine markdown sections with blank lines."""
    return (
        "\n\n".join(section.strip() for section in sections if section.strip()) + "\n"
    )


def write_if_changed(path: Path, content: str, *, check: bool = False) -> bool:
    """Write file only when content changed."""
    if path.exists() and path.read_text() == content:
        print(f"{path} is up to date")
        return True

    if check:
        print(f"{path} is out of date")
        return False

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"Updated {path}")
    return True


def compile_agents(*, check: bool = False) -> bool:
    common = read_markdown(ROOT / "assets" / "agents" / "common_best_practices.md")
    repo_only = read_markdown(
        ROOT / "assets" / "agents" / "repo_development_best_practices.md"
    )
    end_user = read_markdown(ROOT / "assets" / "agents" / "end_user_best_practices.md")

    repo_agents = combine_sections(
        [
            "# AGENTS.md",
            REPO_GENERATED_NOTE,
            common,
            repo_only,
        ]
    )
    ok = write_if_changed(ROOT / "AGENTS.md", repo_agents, check=check)

    lab_agents = combine_sections(
        [
            "# AGENTS.md",
            LAB_GENERATED_NOTE,
            "This AGENTS guide is intended for end users working in a `prime lab setup` workspace.",
            common,
            end_user,
        ]
    )
    ok &= write_if_changed(
        ROOT / "assets" / "lab" / "AGENTS.md", lab_agents, check=check
    )

    repo_claude = combine_sections(
        [
            "# CLAUDE.md",
            REPO_GENERATED_NOTE,
            "Before beginning work in this repository, read `AGENTS.md` and follow all scoped AGENTS guidance.",
        ]
    )
    ok &= write_if_changed(ROOT / "CLAUDE.md", repo_claude, check=check)

    lab_claude = combine_sections(
        [
            "# CLAUDE.md",
            LAB_GENERATED_NOTE,
            "Before beginning any task, read `AGENTS.md`, `AGENTS.local.md` if present, and `environments/AGENTS.md` in this workspace.",
            "Treat all `AGENTS.md` and `AGENTS.local.md` files as equivalent to `CLAUDE.md` files.",
        ]
    )
    ok &= write_if_changed(
        ROOT / "assets" / "lab" / "CLAUDE.md", lab_claude, check=check
    )
    return ok


def compile_environment_guides(*, check: bool = False) -> bool:
    envs_body = read_without_title(ROOT / "docs" / "environments.md")
    repo_envs_agents = combine_sections(
        [
            "# environments/AGENTS.md",
            REPO_GENERATED_NOTE,
            'This file mirrors the "Environments" documentation page.',
            "---",
            envs_body,
        ]
    )
    lab_envs_agents = combine_sections(
        [
            "# environments/AGENTS.md",
            LAB_GENERATED_NOTE,
            'This file mirrors the "Environments" documentation page.',
            "---",
            envs_body,
        ]
    )

    ok = write_if_changed(
        ROOT / "environments" / "AGENTS.md", repo_envs_agents, check=check
    )
    ok &= write_if_changed(
        ROOT / "assets" / "lab" / "environments" / "AGENTS.md",
        lab_envs_agents,
        check=check,
    )
    return ok


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify generated files are current without writing them",
    )
    args = parser.parse_args()
    ok = compile_agents(check=args.check)
    ok &= compile_environment_guides(check=args.check)
    if args.check and not ok:
        sys.exit(1)


if __name__ == "__main__":
    main()
